### ISSUE TITLE
menu items not opening submenu/modal

### ISSUE THREAD

**Issue by sethvincent** [editdata/editdata.org#65]
open dataset, save, export, new column, & new row not currently working

**Comment by kvnneff** [comment]
This shouldn't occur with a fresh `npm i`.  I had to make changes to `menu-element` that I haven't made a PR for yet, so editdata.org relies on `kvnneff/menu-element`.  A bug caused the menu to not work properly but I've since fixed that and it seems to be working on my end.

I'll leave this open until I create a PR for `menu-element`.
