### ISSUE TITLE
grid scroll position bug

### ISSUE THREAD

**Issue by sethvincent** [editdata/editdata.org#67]
- scroll down in the grid
- click a field and make an edit
- when the grid rerenders it is no longer in the same scroll position, but back to showing the top of the grid

i think this might to do with view-list no longer knowing which section of the list it is supposed to be rendering.

**Comment by kvnneff** [comment]
This is a side-effect of using `virtual-app` and a global app state rather than component state.  When a grid cell is clicked it needs to be marked in the app state as `active`, triggering an update in which the grid gets rendered again, losing the scroll position.

One solution would be to keep track of the scroll position in the app state.  A better solution I think would be to use thunks on the `data-grid` module so that if a row/cell is marked `active` in the app state only that row gets rendered again.  Unfortunately I spent a lot of time trying to work thunks into `data-grid` and wasn't successful.

**Comment by kvnneff** [comment]
Actually I was just thinking if the `data-grid` component is aware of the active row/cell anyway we can set the scroll position to center on that element.  That should be pretty easy.

**Comment by kvnneff** [comment]
Scratch that, I forgot the element has to be in the dom to set the scroll position, can't do it from within the component.
